name: cml-2019
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - numpy
  - pip
  - pandas
  - pyarrow
  - python-graphviz
  - scikit-learn
  - matplotlib
  - pip:
    - onnxmltools
    - onnxruntime
